
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package graficadorafinal;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int anaranjado = 24;
  public static final int celeste = 20;
  public static final int rojo = 18;
  public static final int poligono = 9;
  public static final int grande = 31;
  public static final int ovalo = 6;
  public static final int morado = 23;
  public static final int circulo = 5;
  public static final int coma = 14;
  public static final int pequeno = 29;
  public static final int pcoma = 15;
  public static final int pacman = 10;
  public static final int negro = 22;
  public static final int linea = 2;
  public static final int azul = 19;
  public static final int rellena = 16;
  public static final int parAbre = 11;
  public static final int contorno = 17;
  public static final int EOF = 0;
  public static final int estrella = 8;
  public static final int parCierra = 12;
  public static final int gris = 28;
  public static final int error = 1;
  public static final int cuadrado = 3;
  public static final int trianguloRectangulo = 7;
  public static final int verde = 21;
  public static final int entero = 13;
  public static final int rectangulo = 4;
  public static final int amarillo = 27;
  public static final int mediano = 30;
  public static final int rosado = 25;
  public static final int cafe = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "linea",
  "cuadrado",
  "rectangulo",
  "circulo",
  "ovalo",
  "trianguloRectangulo",
  "estrella",
  "poligono",
  "pacman",
  "parAbre",
  "parCierra",
  "entero",
  "coma",
  "pcoma",
  "rellena",
  "contorno",
  "rojo",
  "azul",
  "celeste",
  "verde",
  "negro",
  "morado",
  "anaranjado",
  "rosado",
  "cafe",
  "amarillo",
  "gris",
  "pequeno",
  "mediano",
  "grande"
  };
}

